backend_category_index:
    path:     /
    defaults: { _controller: AppBundle:BackendController/Category:index }

backend_category_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle:BackendController/Category:show }
