backend_category_index:
    path:     /
    defaults: { _controller: AppBundle:BackendController/Category:index }

backend_category_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle:BackendController/Category:show }

backend_category_new:
    path:     /new
    defaults: { _controller: AppBundle:BackendController/Category:new }

backend_category_create:
    path:     /create
    defaults: { _controller: AppBundle:BackendController/Category:create }
