frontend:
    resource: "@AppBundle/Resources/config/Frontend/routing.yml"
    prefix:   /

backend:
     resource: "@AppBundle/Resources/config/Backend/routing.yml"
     prefix:   /backend

slugger:
    path:     /slugger/{string}
    defaults: { _controller: AppBundle:Utils:slugger }
