kind_of_food:
    resource: "@KindOfFoodBundle/Resources/config/routing.yml"
    prefix:   /

nationality:
    resource: "@NationalityBundle/Resources/config/routing.yml"
    prefix:   /

recipe:
    resource: "@RecipeBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

