parameters:
#    user.example.class: CocinamosTodos\UserBundle\Example

services:
#    user.example:
#        class: %user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
