backend_recipe_index:
    path:     /
    defaults: { _controller: AppBundle:BackendController/Recipe:index }

backend_recipe_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle:BackendController/Recipe:show }

backend_recipe_new:
    path:     /new
    defaults: { _controller: AppBundle:BackendController/Recipe:new }

backend_recipe_create:
    path:     /create
    defaults: { _controller: AppBundle:BackendController/Recipe:create }

backend_recipe_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle:BackendController/Recipe:edit }

backend_recipe_update:
    path:     /{id}/update
    defaults: { _controller: AppBundle:BackendController/Recipe:update }

backend_recipe_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle:BackendController/Recipe:delete }
