category_list:
    path:     /list/
    defaults: { _controller: AppBundle:FrontendController/Category:index }

category_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle:FrontendController/Category:show }
